### ISSUE TITLE
application events

### ISSUE THREAD

**Issue by srnerturk** [pinussilvestrus/camunda-modeler-autosave-plugin#8]
How do I catch the shape change event using react? Do you have a list of all events?

sample : 
`subscribe('app.shapeChanged', ({
      element
    }) => {
      alert(element);
    });`

**Comment by pinussilvestrus** [comment]
You can find a list [here](https://github.com/camunda/camunda-modeler/blob/master/CHANGELOG.md#plugins) for all events you can capture with the `subscribe` method. Note that these are _only_ those fired by the React Application. To handle events from the embedded BPMN Editor events, you will have to use the `eventBus`.

```js
subscribe('bpmn.modeler.created', (event) => {

    const {
      modeler,
    } = event;

    const eventBus = modeler.get('eventBus');

    eventBus.on('shape.changed', (event) => {
        console.log('Shape has changed');
    });

 });
```

**Comment by pinussilvestrus** [comment]
The `eventBus` is a component provided by [`bpmn-js`](https://github.com/bpmn-io/bpmn-js), specially from [`diagram-js`](https://github.com/bpmn-io/diagram-js). You can find other events inside these projects, there is no dedicated list currently.

I'll close this issue since it does not relate to any bug or feature request for this project. Feel free to respond if you have any further questions or problems.

In terms you have additional questions, general questions to the Camunda Modeler plugin infrastructure, feel free to[ approach the forum](https://forum.camunda.org/c/modeler).

**Comment by hgedik** [comment]
Hi @pinussilvestrus,

I need event lists for eventBus. I couldn't find any documents about the events (for ex: shape.changed, shape.added). Where can I find a list of events?

**Comment by pinussilvestrus** [comment]
> I need event lists for eventBus. I couldn't find any documents about the events (for ex: shape.changed, shape.added). Where can I find a list of events?

Please see the answer I recently give:

> The eventBus is a component provided by bpmn-js, specially from diagram-js. You can find other events inside these projects, there is no dedicated list currently.

**Comment by pinussilvestrus** [comment]
Basically every feature module and command handlers of diagram-js and bpmn-js provides those events. **There is no complete list**, but you can find those events by scamming the source code. One example: [the `ChangeSupport` module](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/change-support/ChangeSupport.js#L42)

**Comment by pinussilvestrus** [comment]
For futher questions, feel free to move [to the forum](https://forum.bpmn.io/).
